<?php

namespace AppBundle\Repository;

/**
 * RestrictionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestrictionRepository extends \Doctrine\ORM\EntityRepository
{
}
