security:

    encoders:
        AppBundle\Entity\Account:
            algorithm: bcrypt

    providers:
        our_db_provider:
            entity:
                  class: AppBundle:Account
                  property: username
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern: ^/

            provider: our_db_provider
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager

            remember_me:
                secret: '%secret%'
                path: /


            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }