parameters:

services:
    app.file_manager:
        class: AppBundle\Service\FileManager
        arguments: ['%files_directory%']
    app.image_resizer:
        class: AppBundle\Service\ImageResizer
        arguments: []
    app.doctrine_file_listener:
        class: AppBundle\Entity\DoctrineEventListener\FileListener
        arguments: ['@app.file_manager']
        tags:
            - { name: doctrine.orm.entity_listener }
    app.doctrine_photo_listener:
            class: AppBundle\Entity\DoctrineEventListener\PhotoListener
            arguments: ['@app.image_resizer', '@app.file_manager']
            tags:
                - { name: doctrine.orm.entity_listener }
#    app.doctrine_file_upload_listener:
#        class: AppBundle\EventListener\FileUploadListener
#        arguments: ['@app.file_manager', '@app.image_resizer']
#        tags:
#            - { name: doctrine.event_listener, event: prePersist }
#            - { name: doctrine.event_listener, event: preUpdate }
#    app.doctrine_file_delete_listener:
#        class: AppBundle\EventListener\FileDeleteListener
#        arguments: ['@app.file_manager']
#        tags:
#            - { name: doctrine.event_listener, event: preRemove}
#            - { name: doctrine.event_listener, event: preUpdate}
    app.form.type.upload_file:
        class: AppBundle\Form\UploadFileType
        arguments: ['@app.file_manager']
        tags:
            - { name: form.type }